name: Run detekt
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    permissions:
      security-events: write
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew detekt
      - name: Upload SARIF to GitHub using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/detekt.sarif
          category: static-analysis
